In [32]:
import pandas as pd
import numpy as np
from sklearn.neighbors import DistanceMetric

In [33]:
### load csv file, 
### regions: ME, NH, NY

df = pd.read_csv('ushealth05.csv', usecols=range(0,17))
df_ushealth = df.iloc[[19, 29, 32],:]
df_ushealth = df_ushealth.drop(['Area', 'All'], axis=1)
df_ushealth.head(3)

HIV  Malignant  Diabetes  ...  Suicide   Assault  Firearms
19    11.0     3218.0     385.0  ...     175.0     22.0     109.0
29    13.0     2549.0     310.0  ...     162.0     19.0      88.0
32  1644.0    35556.0    4051.0  ...    1189.0    901.0    1019.0

[3 rows x 15 columns]

In [34]:
ushealth_list = np.array(df_ushealth).astype(float)
print("Data dimension: ",np.shape(ushealth_list))
print(ushealth_list)

Data dimension:  (3, 15)
[[1.1000e+01 3.2180e+03 3.8500e+02 4.7600e+02 2.9410e+03 6.9300e+02
  3.5200e+02 8.3000e+02 1.1600e+02 2.5000e+02 5.7900e+02 1.9200e+02
  1.7500e+02 2.2000e+01 1.0900e+02]
 [1.3000e+01 2.5490e+03 3.1000e+02 3.7600e+02 2.5300e+03 4.9700e+02
  2.7300e+02 6.3000e+02 1.1400e+02 1.7300e+02 4.7700e+02 1.6200e+02
  1.6200e+02 1.9000e+01 8.8000e+01]
 [1.6440e+03 3.5556e+04 4.0510e+03 2.0650e+03 5.1985e+04 6.6220e+03
  5.5210e+03 6.8180e+03 1.2240e+03 2.3600e+03 4.6450e+03 1.5300e+03
  1.1890e+03 9.0100e+02 1.0190e+03]]


In [35]:
### Euclidean distance

dist = DistanceMetric.get_metric('euclidean')
dist_eu = np.around(dist.pairwise(ushealth_list), decimals=1, out=None)

print("Euclidean Distance: \n", dist_Euc)

Euclidean Distance: 
 [[    0.    857.1 59950.4]
 [  857.1     0.  60713. ]
 [59950.4 60713.      0. ]]


In [36]:
### Manhattan distance

dist = DistanceMetric.get_metric('manhattan')
dist_man = np.around(dist.pairwise(ushealth_list), decimals=2, out=None)

print("Manhattan Distance: \n", dist_Man)

Manhattan Distance: 
 [[     0.   1980. 116781.]
 [  1980.      0. 118757.]
 [116781. 118757.      0.]]


In [37]:
### Maximum distance

dist = DistanceMetric.get_metric('chebyshev')
dist_max = np.around(dist.pairwise(ushealth_list), decimals=2, out=None)

print("Maximum Distance: \n", dist_Max)

Maximum Distance: 
 [[    0.   669. 49044.]
 [  669.     0. 49455.]
 [49044. 49455.     0.]]
